# Jekyll
permalink: /:year/:month/:title/
paginate: 3
exclude: []
name: CaenCamp
baseurl:
default_locale: fr
current_caencamp:
  title: "CaenCamp #16 :"
  subtitle: Gestion agile de projet et Marché de Noël
  date: le 19 décembre à 18:45
current_dojo:
  title: "Coding Dojo #2 :"
  subtitle: EmberJS/AngularJS
  date: le 16 décembre à 17:30
