# Jekyll
permalink: /:year/:month/:title/
paginate: 3
exclude: []
name: CaenCamp
baseurl:
default_locale: fr
current_caencamp:
  title: "CaenCamp #20"
  subtitle: Apéro-forum sur le thème du télétravail
  date: le 24 avril à partir de 18h00
current_dojo:
  title: "Coding Dojo #4"
  subtitle: Ruby on Rails
  date: courant février
