# Jekyll
markdown: kramdown
permalink: /:year/:month/:title/
paginate: 3
exclude: []
name: CaenCamp
baseurl:
default_locale: fr
current_caencamp:
  title: "CaenCamp #27"
  subtitle: Peut-on travailler proprement avec Wordpress ?
  date: le 4 juin à 18h30
current_dojo:
  title: "Coding Dojo #4"
  subtitle: Ruby on Rails
  date: courant février
