# Jekyll
permalink: /:year/:month/:title/
paginate: 3
exclude: []
name: CaenCamp
baseurl:
default_locale: fr
current_caencamp:
  title: "CaenCamp #19"
  subtitle: Présentation du système GPS
  date: le 27 mars à 18:30
current_dojo:
  title: "Coding Dojo #4"
  subtitle: Ruby on Rails
  date: courant février
