# Jekyll
permalink: /:year/:month/:title/
paginate: 3
exclude: []
name: CaenCamp
baseurl:
default_locale: fr
current_caencamp:
  title: "CaenCamp #17"
  subtitle: Certifications x509 et atelier démos
  date: le 30 janvier à 18:30
current_dojo:
  title: "Coding Dojo #3"
  subtitle: Ruby on Rails
  date: le 13 janvier à 17:30
