# Jekyll
markdown: kramdown
permalink: /:year/:month/:title/
paginate: 3
exclude: []
name: CaenCamp
baseurl:
default_locale: fr
current_caencamp:
  title: "CaenCamp #23"
  subtitle: SVG, format clé du responsive
  date: le 25 septembre à partir de 18h30
current_dojo:
  title: "Coding Dojo #4"
  subtitle: Ruby on Rails
  date: courant février
